### PR TITLE
Use PSR-17 ResponseFactory draft instead of ResponsePrototype

### LINKED ISSUE #3: inject responseFactory into middlewares
follow-up from https://github.com/prooph/event-store-http-middleware/pull/2

### PR DESCRIPTION
**Pull request by codeliner**
Closes #3 

See #4 for discussion

### CODE REVIEW

**Review by prolic — COMMENTED** [review]
Looks good, but where is the JsonTransformer class?

**Comment by codeliner** [comment]
@prolic JsonTransformer is not part of this package.
It needs to be injected: https://github.com/prooph/event-store-http-middleware/pull/5/files#diff-9782dc5d06a5247229375e61a092313eR28
by implementing the `Transformer` interface. I'll add an example implementation (which uses Diactoros JsonResponse) to the docs, so users can copy & paste it, but it is userland implementation.

**Comment by prolic** [comment]
Why not pass the response factory to the json transformer? Then you can set
appropriate headers and json encode the body. So the package has the json
transformer implementation.

**Comment by prolic** [comment]
I'm going to merge this for now, but please let's implement the json-transformer in a separate PR. We don't need a distinct JsonResponse implementation, the default provided by response factory is good enough.

**Pull request merged**
